BASE_URL="http://localhost:8080"
ADD_URL="/add"
UPDATE_URL="/put"
DELETE_URL="/delete"

BOOK_URL=f"{BASE_URL}/book"
ADD_BOOK_URL=f"{BOOK_URL}{ADD_URL}"
UPDATE_BOOK_URL=f"{BOOK_URL}{UPDATE_URL}"
DELETE_BOOK_URL=f"{BOOK_URL}{DELETE_URL}"
