BASE_URL="http://localhost:8080"
ADD_URL="/add"
UPDATE_URL="/put"
DELETE_URL="/delete"

BOOK_URL=f"{BASE_URL}/book"
ADD_BOOK_URL=f"{BOOK_URL}{ADD_URL}"
UPDATE_BOOK_URL=f"{BOOK_URL}{UPDATE_URL}"
DELETE_BOOK_URL=f"{BOOK_URL}{DELETE_URL}"

AUTHOR_URL=f"{BASE_URL}/author"
ADD_AUTHOR_URL=f"{AUTHOR_URL}{ADD_URL}"
UPDATE_AUTHOR_URL=f"{AUTHOR_URL}{UPDATE_URL}"
DELETE_AUTHOR_URL=f"{AUTHOR_URL}{DELETE_URL}"

LIBRARY_URL=f"{BASE_URL}/library"
ADD_LIBRARY_URL=f"{LIBRARY_URL}{ADD_URL}"
UPDATE_LIBRARY_URL=f"{LIBRARY_URL}{UPDATE_URL}"
DELETE_LIBRARY_URL=f"{LIBRARY_URL}{DELETE_URL}"